AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Source Bucket for CodePipeline"

Parameters:
  ProjectName:
    Type: String
    Default: cp002
  Env:
    Type: String
    Description: "Environment code (e.g. dev, stg, prd)"
  AccountCode:
    Type: String
    Description: "Account code (e.g. base, alfa, beta)"
  RegionName:
    Type: String
    Description: "Region name (e.g. tokyo, osaka)"

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub s3-${ProjectName}-${Env}-${AccountCode}-${RegionName}-source
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  SourceBucketName:
    Description: Source bucket name
    Value: !Ref SourceBucket
    Export:
      Name: !Sub ${ProjectName}-${Env}-${AccountCode}-${RegionName}-source-bucket-name
  SourceBucketArn:
    Description: Source bucket ARN
    Value: !GetAtt SourceBucket.Arn
    Export:
      Name: !Sub ${ProjectName}-${Env}-${AccountCode}-${RegionName}-source-bucket-arn
